CREATE TABLE inventario (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL,
  tipo VARCHAR(30) NOT NULL,
  cantidad INT(11) NOT NULL,
  fecha DATE NOT NULL,
  proveedor VARCHAR(30) NOT NULL
  fecha_salida DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;,
)
